apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3Jvb3QxMg== #passroot12
  MYSQL_DATABASE: bXlzcWxkYg== # mysqldb
  MYSQL_USER: YWRtaW4= #admin
  MYSQL_PASSWORD: cGFzczEy #pass12
  
  