apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
  labels:
    type: local-mysql
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: '/Users/abdullahyalcin/Desktop/github-projects/kubernetes-phonebook-project/pv-data'
