apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-server
spec:
  selector:
    matchLabels:
      app: result-server
  template:
    metadata:
      labels:
        app: result-server
    spec:
      containers:
      - name: result-server
        image: abdullahyalcin/result-server
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
