apiVersion: v1
kind: Secret
metadata:
  name: web-secret
type: Opaque
data:
  MYSQL_DATABASE: bXlzcWxkYg== # mysqldb
  MYSQL_USER: YWRtaW4= #admin
  MYSQL_PASSWORD: cGFzczEy #pass12
  MYSQL_DATABASE_HOST: bXlkYg== #mydb