apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-service
  template:
    metadata:
      labels:
        app: web-service
    spec:
      containers:
      - name: web-service
        image: abdullahyalcin/web-server
        envFrom:
          - secretRef:
              name: secret
        ports:
        - containerPort: 80
        resources: {}
